import path from 'node:path';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import type { Db } from './client';
import { createDatabase } from './client';

/**
 * Migrations are plain SQL files generated by drizzle-kit (plus hand-written
 * statements for what it cannot express, e.g. EXCLUDE constraints). They are
 * committed and applied at boot, so `docker compose up` on a fresh volume yields
 * a ready schema. Drizzle records applied files in `drizzle.__drizzle_migrations`.
 */
export async function runMigrations(db: Db): Promise<void> {
  // Resolves to <repo>/backend/drizzle both from src/ (tsx) and dist/ (node).
  const migrationsFolder = path.resolve(__dirname, '../../drizzle');
  await migrate(db, { migrationsFolder });
}

if (require.main === module) {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error('DATABASE_URL is not set');
    process.exit(1);
  }
  const database = createDatabase(url);
  runMigrations(database.db)
    .then(() => console.log('Migrations applied'))
    .catch((err) => {
      console.error(err);
      process.exitCode = 1;
    })
    .finally(() => database.close());
}
